version: '3'
services:
  web:
    build: .
    environment:
      SHEET_ID: 1n9Q_079bXaRNxNjiBr4MOYVVEPagqaFNQSyKUYM6UCY
      REFRESH_TIME: 10000
      QUIZ_TITLE: Thursday Night Quiz - Leaderboard
    ports:
      - "9090:3001"
    expose:
      - "3001"
    volumes:
      - ${PWD}/privatekey.json /usr/app/src/privatekey.json
    restart: always
    command: ls /usr/app/src